apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mini-jira-app
  namespace: argocd
spec:
  project: mini-jira-project
  source:
    repoURL: 'https://github.com/Devvrma/mini-jira-devops.git'
    targetRevision: HEAD
    path: kuberentes
    directory:
      recurse: true
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true