apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: mini-jira-project
  namespace: argocd
spec:
  description: "Project for Mini Jira DevOps Stack"
  # Allow deployment to any cluster (we are using in-cluster/local)
  destinations:
    - namespace: '*'
      server: '*'
  # Allow pulling resources from our Git repository only
  sourceRepos:
    - '*'