apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: mini-jira-project
  namespace: argocd
spec:
  description: "Project for Mini Jira DevOps Stack"
  destinations:
    - namespace: '*'
      server: '*'
  sourceRepos:
    - '*'