apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: minijira-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    # 👇 Yeh sirf specify karta hai ki nginx ingress use ho raha hai
spec:
  rules:
  - host: mini-jira.local
    http:
      paths:
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: backend
            port:
              number: 8000
      - path: /
        pathType: Prefix
        backend:
          service:
            name: frontend
            port:
              number: 3000