name: Backend CI Pipeline

on:
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Debug
        run: |
          echo "USERNAME=${{ secrets.DOCKERHUB_USERNAME }}"
          echo "TAG=devverma99/minijira-backend:latest"

      - name: Login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Image
        run: |
          docker build -t devverma99/minijira-backend:latest ./backend

      - name: Push Image
        run: |
          docker push devverma99/minijira-backend:latest